language: csharp

before_install:
  - git submodule update --init --recursive

mono:
    - latest
    - 4.6.1
    - 4.2.3
    - 4.2.1
    - 4.0.0
    - 3.12.0
    - 3.2.8
    - 2.10.8

install:
    - sudo apt-get update > /dev/null
    - sudo apt-get build-dep smuxi > /dev/null
    - sudo apt-get install devscripts equivs > /dev/null
    - sudo mk-build-deps --install debian/control > /dev/null
    - sudo apt-get install mono-devel nunit-console moreutils gtk-sharp2-gapi libgtkspell-dev > /dev/null

script:
    - ./autogen.sh MCS=/usr/bin/dmcs
    - find lib/ -name "*.csproj" -exec sed 's!<WarningLevel>[0-9]</WarningLevel>!<WarningLevel>0</WarningLevel>!' -i {} \;
    - sed 's!<Package>dbus-sharp-2.0</Package>!<Package>dbus-sharp-1.0</Package>!' -i src/Frontend-GNOME/Frontend-GNOME.csproj
    - sed 's!<Package>dbus-sharp-glib-2.0</Package>!<Package>dbus-sharp-glib-1.0</Package>!' -i src/Frontend-GNOME/Frontend-GNOME.csproj
    - sed 's!dbus-sharp, Version=2.0.0.0,!dbus-sharp, Version=1.0.0.0,!' -i src/Frontend-GNOME/Frontend-GNOME.csproj
    - sed 's!dbus-sharp-glib, Version=2.0.0.0,!dbus-sharp-glib, Version=1.0.0.0,!' -i src/Frontend-GNOME/Frontend-GNOME.csproj
    - |
      if test -e /usr/lib/mono/4.5/mscorlib.dll; then
        xbuild /p:Warn=0 src/smuxi.sln
      else
        xbuild /p:Warn=0 src/smuxi.sln /p:TargetFrameworkVersion=v4.0
      fi
    - nunit-console bin/release/smuxi-common-tests.dll
    - nunit-console bin/release/smuxi-engine-tests.dll
    - nunit-console bin/release/smuxi-frontend-tests.dll
    - nunit-console bin/release/smuxi-frontend-gnome-tests.dll
    - nunit-console bin/release/smuxi-frontend-stfl-tests.dll
    - chronic make clean && chronic make distcheck MCS=/usr/bin/dmcs
    - export DEB_UPSTREAM_VERSION=$(dpkg-parsechangelog -ldebian/changelog | grep ^Vers | cut -d\  -f2 | cut -d':' -f2 | sed 's,-.*,,' | sed 's,+dfsg.*,,')
    - mv smuxi-*.tar.gz ../smuxi_${DEB_UPSTREAM_VERSION}.orig.tar.gz
    - cd .. && tar -xzf smuxi_${DEB_UPSTREAM_VERSION}.orig.tar.gz
    - cd - && cp -a debian/ ../smuxi-*/
    - cd ../smuxi-* && chronic dpkg-buildpackage -us -uc

notifications:
    irc:
        channels: "chat.freenode.net#smuxi-devel"
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
